### ISSUE TITLE
Setup code quality tools for JavaScript and TypeScript.

### ISSUE THREAD

**Issue by kasunkv** [99xt/protractor-starter#24]
Need to setup code quality tool to initially check JavaScript and TypeScript. After the code base is fully moved to TypeScript only type script code quality will remain.

**Comment by rehrumesh** [comment]
[Codacy](https://www.codacy.com/) may be a good tool. They provide free plans for Open source projects.

**Comment by charithsoori** [comment]
check this https://www.codacy.com/app/charithsoori/protractor-starter/dashboard

**Comment by charithsoori** [comment]
Nice . Let's take this to organization level

Thanks & regards,

Charith Sooriyaarachchi

Associate Tech Lead /Engineer - 99x Technology.
Mobile: +94775423273
@charithsoori

**Comment by kasunkv** [comment]
Codacy does not detect or analyze TypeScript by default. There is an option to include .ts extension in the JavaScript detection but i'm not sure how much would this work with TS. We need to setup a different method to analyze TypeScript. May be TSLint would be a good option. Closing this issue due to JS analysis support is already added with Codacy.

**Comment by charithsoori** [comment]
Good, you raised this issue . We should probably find a standard way . Let's integrate your finding to organization level or come up with a guideline
